### PR TITLE
Use NLTK from wheels repo

### PR DESCRIPTION
**Pull request by Ladsgroup**

### CODE REVIEW

**Comment by Ladsgroup** [comment]
I tested it indirectly

**Comment by halfak** [comment]
Why not just leave the data in the submodule directory and then change the main config to point to that directory?

**Comment by halfak** [comment]
Also, please note how you tested so that if I get different results, I know why.

**Comment by Ladsgroup** [comment]
let me try that :)

**Comment by halfak** [comment]
I started up ores_wsgi.py, watched all the models load.  I loaded up `http://localhost:5000/scores/enwiki/reverted/?revids=10000` and it worked as expected.

**Pull request merged**
